### PR TITLE
Make make_new_application.py compatible with both python2 and python3

### PR DESCRIPTION
**Pull request by lindsayad**
- Replace `print 'text'` with `print('text')`
- Use `str.upper()` and `str.lower()` instead of `string.upper()` and `string.lower()`
- Use the encoding option from io's `open` such that python3 can read in the test exodus binary

### CODE REVIEW

**Comment by friedmud** [comment]
I'm not for this change (but I can be overruled).

The entire MOOSE ecosystem depends on Python2.  We shouldn't give any false hope of anything ever working with Python3.

Years from now we'll do a "big switch"... but that time isn't here yet.

**Comment by permcody** [comment]
As long as it's backwards compatible, this is fine. We've had people put in Python3 "fixes" before that do NOT work with python 2.6 (our current minimum version). That'll be the test for this one PR before we merge.

Thanks Alex!

**Comment by lindsayad** [comment]
Thanks Cody.

If the goal is to be compatible with python 2.6, then the call to subprocess.check_output [here](https://github.com/idaholab/stork/blob/master/make_new_application.py#L121)  is going to produce an AttributeError.

**Comment by lindsayad** [comment]
In terms of stork use, the only evidence I have of people trying (and failing) to use a python version < 2.7 comes from the message board: https://groups.google.com/forum/#!searchin/moose-users/subprocess.check_output%7Csort:relevance/moose-users/qq9KhzfQF98/a-pAMdxx5MYJ, where @permcody suggests he's using "a very old version of python" :-) Are we sure we need to be backwards compatible with versions < 2.7?

**Comment by permcody** [comment]
touché...

 We upped our minimum version to 2.7 somewhat recently but I had forgotten.
Thanks for digging that up.

**Comment by lindsayad** [comment]
I assume that you're going to test on your end? I've tested on both 2.7 and 3.5

**Comment by lindsayad** [comment]
This is deprecated, so I don't care anymore.

**Pull request closed without merging**
